apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: focalboard
namePrefix: focalboard-

images:
  - name: mattermost/focalboard
    newTag: 7.4.4

configMapGenerator:
- name: app-env
  literals:
  - VIRTUAL_HOST=focalboard.local
  - VIRTUAL_PORT=8000
  options:
    disableNameSuffixHash: true
    labels:
      io.focalboard.service: app-env

resources:
  - './resources/namespace.yaml'
  - './resources/claims.yaml'
  - './resources/deployments/app.yaml'
  - './resources/services/app.yaml'
