---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    io.focalboard.service: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.focalboard.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.focalboard.service: app
    spec:
      containers:
        - image: mattermost/focalboard:latest
          name: app
          envFrom:
          - configMapRef:
              name: app-env
          ports:
            - containerPort: 8000
              name: app
          volumeMounts:
            - mountPath: /data
              name: data-storage
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1024Mi
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: app-data-pvc
